### ISSUE TITLE
Shox genes not always producing X and Y mappings

### ISSUE THREAD

**Issue by i3hsInnovation** [openvar/variantValidator#252]
Sure!
Fetching transcripts, getting locations on X and Y:
https://www35.lamp.le.ac.uk/VariantValidator/tools/gene2transcripts/SHOX?content-type=application%2Fjson

LOVD deleting a base inside this region on X:
https://www35.lamp.le.ac.uk/LOVD/lovd/hg19/NC_000023.10%3Ag.591732del/all/all/tx/True?content-type=application%2Fjson

**Comment by i3hsInnovation** [comment]
https://github.com/openvar/variantValidator/issues/251

**Comment by i3hsInnovation** [comment]
The variant is `NC_000023.10:g.591732del` 
https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000023.10%3Ag.591732del/all?content-type=application%2Fjson for VV

Note, VV does find chrY GRCh37 and adds to ALT

```json
    "alt_genomic_loci": [
      {
        "grch38": {
          "hgvs_genomic_description": "NC_000024.10:g.630997del",
          "vcf": {
            "alt": "T",
            "chr": "Y",
            "pos": "630996",
            "ref": "TA"
          }
        }
      },
      {
        "hg38": {
          "hgvs_genomic_description": "NC_000024.10:g.630997del",
          "vcf": {
            "alt": "T",
            "chr": "chrY",
            "pos": "630996",
            "ref": "TA"
          }
        }
      },
      {
        "grch37": {
          "hgvs_genomic_description": "NC_000024.9:g.541732del",
          "vcf": {
            "alt": "T",
            "chr": "Y",
            "pos": "541731",
            "ref": "TA"
          }
        }
      },
      {
        "hg19": {
          "hgvs_genomic_description": "NC_000024.9:g.541732del",
          "vcf": {
            "alt": "T",
            "chr": "chrY",
            "pos": "541731",
            "ref": "TA"
          }
        }
      }
    ],
```

The LOVD endpoint misses it. 
```json
"primary_assembly_loci": {
"grch37": {
"NC_000023.10": {
"hgvs_genomic_description": "NC_000023.10:g.591732del",
"vcf": {
"alt": "T",
"chr": "X",
"pos": "591731",
"ref": "TA"
}
}
},
"grch38": {
"NC_000023.11": {
"hgvs_genomic_description": "NC_000023.11:g.630997del",
"vcf": {
"alt": "T",
"chr": "X",
"pos": "630996",
"ref": "TA"
}
},
"NC_000024.10": {
"hgvs_genomic_description": "NC_000024.10:g.630997del",
"vcf": {
"alt": "T",
"chr": "Y",
"pos": "630996",
"ref": "TA"
}
}
},
"hg19": {
"NC_000023.10": {
"hgvs_genomic_description": "NC_000023.10:g.591732del",
"vcf": {
"alt": "T",
"chr": "chrX",
"pos": "591731",
"ref": "TA"
}
}
},
"hg38": {
"NC_000023.11": {
"hgvs_genomic_description": "NC_000023.11:g.630997del",
"vcf": {
"alt": "T",
"chr": "chrX",
"pos": "630996",
"ref": "TA"
}
},
"NC_000024.10": {
"hgvs_genomic_description": "NC_000024.10:g.630997del",
"vcf": {
"alt": "T",
"chr": "chrY",
"pos": "630996",
"ref": "TA"
}
}
}
},
```

Take a look at VF

**Comment by i3hsInnovation** [comment]
Issue sorted by a bit of lateral thinking. Will push up shortly then update the servers before knocking off tonight.

**Comment by i3hsInnovation** [comment]
https://github.com/openvar/variantValidator/commit/2ab2e2f4d1f8526dc0e081dd0a35a6a77fcdfae1

**Comment by ifokkema** [comment]
Thanks!!!

**Comment by PeteCausey-Freeman** [comment]
I deployed last night @ifokkema . Should be working for you

**Comment by ifokkema** [comment]
Hi Pete,
I'm going through some old emails & issues and found some issues for which I can't find the fix yet. For instance, this issue. Which URL is currently running the latest VV?
Related; I also noticed chrX is sometimes referred to as `X`, and sometimes as `chrX`, depending on the genome build. Is it supposed to be that way, or is this by mistake? Should I open an issue?

**Comment by ifokkema** [comment]
> The latest VV is running on rest.variantvalidator.org

Hmm... in that case, this bug isn't fixed?


> Also, when you select a GRCh build, you will get `X` because this is the preferred syntax used by RefSeq. If you select a hg build, you will see `chrX` because this is the preferred syntax used by UCSC. So this is correct. I personally would not use hg19 and hg38 but instead stick to GECh37 and GRCh38.

Ah, clear, thanks!!

**Comment by PeteCausey-Freeman** [comment]
> Hmm... in that case, this bug isn't fixed? 

Ah, that I wasn't expecting. I wonder if I forgot to merge something. Can you please provide a couple of variants. I will also check the test files because I add tests for each issue. I have the example NC_000023.10:g.591732del. Have you got a few more? 

I'm confused as to why this isnt fixed if I said it was. Yuk. Coffee needed. Brain error!!!!

**Comment by ifokkema** [comment]
> > Hmm... in that case, this bug isn't fixed?
> 
> Ah, that I wasn't expecting.

Hehe yeah for a minute there I was wondering if maybe the main URL wasn't updated even though the versions looked good 😅

> Can you please provide a couple of variants.

So what I normally do is just check the reported variants and see if they work now - in this case, it doesn't. If you want more examples, I've checked two variants from LOVD from both ends of the gene;

https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000023.10%3Ag.591694G%3EA/all/NM_006883.2/tx/True?content-type=application%2Fjson
https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000023.10%3Ag.619563G%3EA/all/NM_006883.2/tx/True?content-type=application%2Fjson

Neither provide mappings on chrY. There's no difference whether I submit as hg19 or GRCh37.


> I'm confused as to why this isnt fixed if I said it was. Yuk. Coffee needed. Brain error!!!!

Haha, no worries! When there's a lot going on all at the same time, it's really hard to keep everything separated.

**Comment by PeteCausey-Freeman** [comment]
Found some un-merged commits. Try now.

**Comment by PeteCausey-Freeman** [comment]
No. Still not fixed. I'll look through the commits again

**Comment by PeteCausey-Freeman** [comment]
Ah. Wait,  that's not quite right either but closer

**Comment by PeteCausey-Freeman** [comment]
OK now got this on my dev

http://127.0.0.1:5000/LOVD/lovd/GRCh37/NC_000023.10%3Ag.591732del/refseq/all/False/True?content-type=application%2Fjson

```json
{
  "NC_000023.10:g.591732del": {
    "NC_000023.10:g.591732del": {
      "g_hgvs": "NC_000023.10:g.591732del",
      "genomic_variant_error": null,
      "hgvs_t_and_p": {
        "NM_000451.3": {
          "alt_genomic_loci": {
            "grch37": {},
            "grch38": {},
            "hg19": {},
            "hg38": {}
          },
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_000442.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_000442.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              },
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              },
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              },
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              },
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_000451.3:c.100del",
          "transcript_variant_error": null
        },
        "NM_006883.2": {
          "alt_genomic_loci": {
            "grch37": {},
            "grch38": {},
            "hg19": {},
            "hg38": {}
          },
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_006874.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_006874.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              },
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              },
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              },
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              },
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_006883.2:c.100del",
          "transcript_variant_error": null
        }
      },
      "p_vcf": "X:591731:TA:T",
      "selected_build": "GRCh37"
    },
    "errors": [],
    "flag": null
  },
  "metadata": {
    "variantformatter_version": "1.0.2.dev20+ge725d86.d20211116",
    "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
    "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
    "vvdb_version": "vvdb_2021_4",
    "vvseqrepo_db": "VV_SR_2021_2/master",
    "vvta_version": "vvta_2021_2"
  }
}
```

Think it looks correct now

**Comment by ifokkema** [comment]
Previously, it was in the `alt_genomic_loci` key. If it'll become primary, we'd need to make some adjustments on our side.

**Comment by PeteCausey-Freeman** [comment]
That was in VV no? Think it still is. This is the LOVD function. Testing the VV now

**Comment by PeteCausey-Freeman** [comment]
Yep VV puts it into Alts
https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh37/NC_000023.10%3Ag.591732del/all?content-type=application%2Fjson

```json
{
"NM_000451.3:c.100del": {
"alt_genomic_loci": [
{
"grch38": {
"hgvs_genomic_description": "NC_000024.10:g.630997del",
"vcf": {
"alt": "T",
"chr": "Y",
"pos": "630996",
"ref": "TA"
}
}
},
{
"hg38": {
"hgvs_genomic_description": "NC_000024.10:g.630997del",
"vcf": {
"alt": "T",
"chr": "chrY",
"pos": "630996",
"ref": "TA"
}
}
},
{
"grch37": {
"hgvs_genomic_description": "NC_000024.9:g.541732del",
"vcf": {
"alt": "T",
"chr": "Y",
"pos": "541731",
"ref": "TA"
}
}
},
{
"hg19": {
"hgvs_genomic_description": "NC_000024.9:g.541732del",
"vcf": {
"alt": "T",
"chr": "chrY",
"pos": "541731",
"ref": "TA"
}
}
}
],
"annotations": {
"chromosome": [
"X",
"Y"
],
"db_xref": {
"CCDS": "CCDS14107.1",
"ensemblgene": null,
"hgnc": "HGNC:10853",
"ncbigene": "6473",
"select": "MANE"
},
"ensembl_select": false,
"mane_plus_clinical": false,
"mane_select": true,
"map": "Xp22.33 and Yp11.32",
"note": "short stature homeobox",
"refseq_select": true,
"variant": "1"
},
"gene_ids": {
"ccds_ids": [
"CCDS14106",
"CCDS14107"
],
"ensembl_gene_id": "ENSG00000185960",
"entrez_gene_id": "6473",
"hgnc_id": "HGNC:10853",
"omim_id": [
"312865",
"400020"
],
"ucsc_id": "uc004fou.1"
},
"gene_symbol": "SHOX",
"genome_context_intronic_sequence": "",
"hgvs_lrg_transcript_variant": "LRG_710t1:c.100del",
"hgvs_lrg_variant": "LRG_710:g.11654del",
"hgvs_predicted_protein_consequence": {
"lrg_slr": "LRG_710p1:p.(T34Rfs*42)",
"lrg_tlr": "LRG_710p1:p.(Thr34ArgfsTer42)",
"slr": "NP_000442.1:p.(T34Rfs*42)",
"tlr": "NP_000442.1:p.(Thr34ArgfsTer42)"
},
"hgvs_refseqgene_variant": "NG_009385.2:g.11654del",
"hgvs_transcript_variant": "NM_000451.3:c.100del",
"primary_assembly_loci": {
"grch37": {
"hgvs_genomic_description": "NC_000023.10:g.591732del",
"vcf": {
"alt": "T",
"chr": "X",
"pos": "591731",
"ref": "TA"
}
},
"grch38": {
"hgvs_genomic_description": "NC_000023.11:g.630997del",
"vcf": {
"alt": "T",
"chr": "X",
"pos": "630996",
"ref": "TA"
}
},
"hg19": {
"hgvs_genomic_description": "NC_000023.10:g.591732del",
"vcf": {
"alt": "T",
"chr": "chrX",
"pos": "591731",
"ref": "TA"
}
},
"hg38": {
"hgvs_genomic_description": "NC_000023.11:g.630997del",
"vcf": {
"alt": "T",
"chr": "chrX",
"pos": "630996",
"ref": "TA"
}
}
},
"reference_sequence_records": {
"lrg": "http://ftp.ebi.ac.uk/pub/databases/lrgex/pending/LRG_710.xml",
"protein": "https://www.ncbi.nlm.nih.gov/nuccore/NP_000442.1",
"refseqgene": "https://www.ncbi.nlm.nih.gov/nuccore/NG_009385.2",
"transcript": "https://www.ncbi.nlm.nih.gov/nuccore/NM_000451.3"
},
"refseqgene_context_intronic_sequence": "",
"selected_assembly": "GRCh37",
"submitted_variant": "NC_000023.10:g.591732del",
"transcript_description": "Homo sapiens short stature homeobox (SHOX), transcript variant 1, mRNA",
"validation_warnings": [
"Removing redundant reference bases from variant description",
"The current status of LRG_710 is pending therefore changes may be made to the LRG reference sequence"
],
"variant_exonic_positions": {
"NC_000023.10": {
"end_exon": "2",
"start_exon": "2"
},
"NC_000023.11": {
"end_exon": "2",
"start_exon": "2"
},
"NG_009385.2": {
"end_exon": "2",
"start_exon": "2"
}
}
},
"NM_006883.2:c.100del": {
"alt_genomic_loci": [
{
"grch38": {
"hgvs_genomic_description": "NC_000024.10:g.630997del",
"vcf": {
"alt": "T",
"chr": "Y",
"pos": "630996",
"ref": "TA"
}
}
},
{
"hg38": {
"hgvs_genomic_description": "NC_000024.10:g.630997del",
"vcf": {
"alt": "T",
"chr": "chrY",
"pos": "630996",
"ref": "TA"
}
}
},
{
"grch37": {
"hgvs_genomic_description": "NC_000024.9:g.541732del",
"vcf": {
"alt": "T",
"chr": "Y",
"pos": "541731",
"ref": "TA"
}
}
},
{
"hg19": {
"hgvs_genomic_description": "NC_000024.9:g.541732del",
"vcf": {
"alt": "T",
"chr": "chrY",
"pos": "541731",
"ref": "TA"
}
}
}
],
"annotations": {
"chromosome": [
"X",
"Y"
],
"db_xref": {
"CCDS": "CCDS14106.1",
"ensemblgene": null,
"hgnc": "HGNC:10853",
"ncbigene": "6473",
"select": false
},
"ensembl_select": false,
"mane_plus_clinical": false,
"mane_select": false,
"map": "Xp22.33 and Yp11.32",
"note": "short stature homeobox",
"refseq_select": false,
"variant": "2"
},
"gene_ids": {
"ccds_ids": [
"CCDS14106",
"CCDS14107"
],
"ensembl_gene_id": "ENSG00000185960",
"entrez_gene_id": "6473",
"hgnc_id": "HGNC:10853",
"omim_id": [
"312865",
"400020"
],
"ucsc_id": "uc004fou.1"
},
"gene_symbol": "SHOX",
"genome_context_intronic_sequence": "",
"hgvs_lrg_transcript_variant": "LRG_710t2:c.100del",
"hgvs_lrg_variant": "LRG_710:g.11654del",
"hgvs_predicted_protein_consequence": {
"lrg_slr": "LRG_710p2:p.(T34Rfs*42)",
"lrg_tlr": "LRG_710p2:p.(Thr34ArgfsTer42)",
"slr": "NP_006874.1:p.(T34Rfs*42)",
"tlr": "NP_006874.1:p.(Thr34ArgfsTer42)"
},
"hgvs_refseqgene_variant": "NG_009385.2:g.11654del",
"hgvs_transcript_variant": "NM_006883.2:c.100del",
"primary_assembly_loci": {
"grch37": {
"hgvs_genomic_description": "NC_000023.10:g.591732del",
"vcf": {
"alt": "T",
"chr": "X",
"pos": "591731",
"ref": "TA"
}
},
"grch38": {
"hgvs_genomic_description": "NC_000023.11:g.630997del",
"vcf": {
"alt": "T",
"chr": "X",
"pos": "630996",
"ref": "TA"
}
},
"hg19": {
"hgvs_genomic_description": "NC_000023.10:g.591732del",
"vcf": {
"alt": "T",
"chr": "chrX",
"pos": "591731",
"ref": "TA"
}
},
"hg38": {
"hgvs_genomic_description": "NC_000023.11:g.630997del",
"vcf": {
"alt": "T",
"chr": "chrX",
"pos": "630996",
"ref": "TA"
}
}
},
"reference_sequence_records": {
"lrg": "http://ftp.ebi.ac.uk/pub/databases/lrgex/pending/LRG_710.xml",
"protein": "https://www.ncbi.nlm.nih.gov/nuccore/NP_006874.1",
"refseqgene": "https://www.ncbi.nlm.nih.gov/nuccore/NG_009385.2",
"transcript": "https://www.ncbi.nlm.nih.gov/nuccore/NM_006883.2"
},
"refseqgene_context_intronic_sequence": "",
"selected_assembly": "GRCh37",
"submitted_variant": "NC_000023.10:g.591732del",
"transcript_description": "Homo sapiens short stature homeobox (SHOX), transcript variant 2, mRNA",
"validation_warnings": [
"Removing redundant reference bases from variant description",
"The current status of LRG_710 is pending therefore changes may be made to the LRG reference sequence"
],
"variant_exonic_positions": {
"NC_000023.10": {
"end_exon": "2",
"start_exon": "2"
},
"NC_000023.11": {
"end_exon": "2",
"start_exon": "2"
},
"NG_009385.2": {
"end_exon": "2",
"start_exon": "2"
}
}
},
"flag": "gene_variant",
"metadata": {
"variantvalidator_hgvs_version": "2.0.1",
"variantvalidator_version": "2.0.1.dev20+g8b67212",
"vvdb_version": "vvdb_2021_4",
"vvseqrepo_db": "VV_SR_2021_2/master",
"vvta_version": "vvta_2021_2"
}
}
```

**Comment by PeteCausey-Freeman** [comment]
Im pretty sure @ifokkema that ages ago you said your preference was to have the Y chr in primary but I was restricted by what I could do with the VV endpoint so we decided to keep it in primary for LOVD endpoint. Let me know if you want this altered

**Comment by ifokkema** [comment]
That I can't remember - consistency is the most important part here. We can work around it if needed, but it's important we can find it in the same place. We use both LOVD and VV endpoints; the chrY mappings should be in the same location there. So if VV restricts you to the alt builds, then it's best to do the same for the LOVD endpoint :sweat_smile: 
Thanks!!!

**Comment by PeteCausey-Freeman** [comment]
Done
```json
{
  "NC_000023.10:g.591732del": {
    "NC_000023.10:g.591732del": {
      "g_hgvs": "NC_000023.10:g.591732del",
      "genomic_variant_error": null,
      "hgvs_t_and_p": {
        "NM_000451.3": {
          "alt_genomic_loci": {
            "grch37": {
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_000442.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_000442.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_000451.3:c.100del",
          "transcript_variant_error": null
        },
        "NM_006883.2": {
          "alt_genomic_loci": {
            "grch37": {
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000024.9": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000024.10": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_006874.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_006874.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_006883.2:c.100del",
          "transcript_variant_error": null
        }
      },
      "p_vcf": "X:591731:TA:T",
      "selected_build": "GRCh37"
    },
    "errors": [],
    "flag": null
  },
  "metadata": {
    "variantformatter_version": "1.0.2.dev20+ge725d86.d20211116",
    "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
    "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
    "vvdb_version": "vvdb_2021_4",
    "vvseqrepo_db": "VV_SR_2021_2/master",
    "vvta_version": "vvta_2021_2"
  }
}
```

**Comment by PeteCausey-Freeman** [comment]
OK, close now
```json
{
  "NC_000023.10:g.591732del": {
    "NC_000023.10:g.591732del": {
      "g_hgvs": "NC_000023.10:g.591732del",
      "genomic_variant_error": null,
      "hgvs_t_and_p": {
        "NM_000451.3": {
          "alt_genomic_loci": [
            {
              "grch37": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "hg19": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "grch38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            {
              "hg38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          ],
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_000442.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_000442.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_000451.3:c.100del",
          "transcript_variant_error": null
        },
        "NM_006883.2": {
          "alt_genomic_loci": [
            {
              "grch37": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "hg19": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "grch38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            {
              "hg38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          ],
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_006874.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_006874.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000023.10",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_006883.2:c.100del",
          "transcript_variant_error": null
        }
      },
      "p_vcf": "X:591731:TA:T",
      "selected_build": "GRCh37"
    },
    "errors": [],
    "flag": null
  },
  "metadata": {
    "variantformatter_version": "1.0.2.dev25+g7d8018e.d20220317",
    "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
    "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
    "vvdb_version": "vvdb_2021_4",
    "vvseqrepo_db": "VV_SR_2021_2/master",
    "vvta_version": "vvta_2021_2"
  }
```

This looks correct now @ifokkema and ought to be all but identical to the VV output for alt_loci. Perhaps in a different order but same content. 

```json
"alt_genomic_loci": [
      {
        "grch38": {
          "hgvs_genomic_description": "NC_000024.10:g.630997del",
          "vcf": {
            "alt": "T",
            "chr": "Y",
            "pos": "630996",
            "ref": "TA"
          }
        }
      },
      {
        "hg38": {
          "hgvs_genomic_description": "NC_000024.10:g.630997del",
          "vcf": {
            "alt": "T",
            "chr": "chrY",
            "pos": "630996",
            "ref": "TA"
          }
        }
      },
      {
        "grch37": {
          "hgvs_genomic_description": "NC_000024.9:g.541732del",
          "vcf": {
            "alt": "T",
            "chr": "Y",
            "pos": "541731",
            "ref": "TA"
          }
        }
      },
      {
        "hg19": {
          "hgvs_genomic_description": "NC_000024.9:g.541732del",
          "vcf": {
            "alt": "T",
            "chr": "chrY",
            "pos": "541731",
            "ref": "TA"
          }
        }
      }
    ],
```

Just need to check a position with ALT chrs to make sure they are still processing correctly

**Comment by PeteCausey-Freeman** [comment]
This is the test for an alt genomic position

```json
"alt_genomic_loci": [
            {
              "grch38": {
                "hgvs_genomic_description": "NT_187607.1:g.1396662_1396663inv",
                "vcf": {
                  "alt": "AC",
                  "chr": "HSCHR16_1_CTG1",
                  "pos": "1396662",
                  "ref": "GT"
                }
              }
            },
            {
              "hg38": {
                "hgvs_genomic_description": "NT_187607.1:g.1396662_1396663inv",
                "vcf": {
                  "alt": "AC",
                  "chr": "chr16_KI270853v1_alt",
                  "pos": "1396662",
                  "ref": "GT"
                }
              }
            }
          ],
```

**Comment by PeteCausey-Freeman** [comment]
Should be live now @ifokkema

**Comment by ifokkema** [comment]
Great! But... I just noticed a minor issue, sorry! :sweat_smile: 
We don't use the "chr" field (we just take the HGVS descriptions), but there are some inconsistencies.

See [this output](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000023.10%3Ag.591732del/all/NM_000451.3/tx/primary?content-type=application%2Fjson):
```json
{
  "NC_000023.10:g.591732del": {
    "NC_000023.10:g.591732del": {
      "g_hgvs": "NC_000023.10:g.591732del",
      "genomic_variant_error": null,
      "hgvs_t_and_p": {
        "NM_000451.3": {
          "alt_genomic_loci": [
            {
              "grch37": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9", /* should be "chrY" */
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "hg19": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "NC_000024.9", /* should be "Y" */
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
```

This is in both alt and primary lists, and only for hg19/GRCh37; hg38/GRCh38 shows "Y"/"chrY" as expected.

Sorry to keep you busy!

**Comment by PeteCausey-Freeman** [comment]
Oh, that's true enough. Should be an easy fix. Thanks

**Comment by PeteCausey-Freeman** [comment]
Fixed
```json
{
  "NC_000023.10:g.591732del": {
    "NC_000023.10:g.591732del": {
      "g_hgvs": "NC_000023.10:g.591732del",
      "genomic_variant_error": null,
      "hgvs_t_and_p": {
        "NM_000451.3": {
          "alt_genomic_loci": [
            {
              "grch37": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "hg19": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "grch38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            {
              "hg38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          ],
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_000442.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_000442.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_000451.3:c.100del",
          "transcript_variant_error": null
        },
        "NM_006883.2": {
          "alt_genomic_loci": [
            {
              "grch37": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "hg19": {
                "hgvs_genomic_description": "NC_000024.9:g.541732del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "541731",
                  "ref": "TA"
                }
              }
            },
            {
              "grch38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "Y",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            {
              "hg38": {
                "hgvs_genomic_description": "NC_000024.10:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrY",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          ],
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_006874.1:p.(T34Rfs*42)",
          "p_hgvs_tlc": "NP_006874.1:p.(Thr34ArgfsTer42)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "grch38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "X",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            },
            "hg19": {
              "NC_000023.10": {
                "hgvs_genomic_description": "NC_000023.10:g.591732del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "591731",
                  "ref": "TA"
                }
              }
            },
            "hg38": {
              "NC_000023.11": {
                "hgvs_genomic_description": "NC_000023.11:g.630997del",
                "vcf": {
                  "alt": "T",
                  "chr": "chrX",
                  "pos": "630996",
                  "ref": "TA"
                }
              }
            }
          },
          "t_hgvs": "NM_006883.2:c.100del",
          "transcript_variant_error": null
        }
      },
      "p_vcf": "X:591731:TA:T",
      "selected_build": "GRCh37"
    },
    "errors": [],
    "flag": null
  },
  "metadata": {
    "variantformatter_version": "1.0.2.dev25+g7d8018e.d20220317",
    "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
    "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
    "vvdb_version": "vvdb_2021_4",
    "vvseqrepo_db": "VV_SR_2021_2/master",
    "vvta_version": "vvta_2021_2"
  }
}
```

Will upload once tests complete

**Comment by ifokkema** [comment]
Excellent, thanks a lot!
